"""
Chart Generator — produces self-contained HTML files with Chart.js visualizations.

Supports bar, line, pie, doughnut, scatter, and horizontal bar charts.
Also generates multi-chart dashboard HTML pages.
"""

import json
import os
from datetime import datetime


# Curated color palettes for charts
CHART_COLORS = [
    "rgba(99, 102, 241, 0.85)",   # Indigo
    "rgba(16, 185, 129, 0.85)",   # Emerald
    "rgba(245, 158, 11, 0.85)",   # Amber
    "rgba(239, 68, 68, 0.85)",    # Red
    "rgba(139, 92, 246, 0.85)",   # Violet
    "rgba(14, 165, 233, 0.85)",   # Sky
    "rgba(236, 72, 153, 0.85)",   # Pink
    "rgba(34, 197, 94, 0.85)",    # Green
    "rgba(251, 146, 60, 0.85)",   # Orange
    "rgba(168, 85, 247, 0.85)",   # Purple
    "rgba(6, 182, 212, 0.85)",    # Cyan
    "rgba(244, 63, 94, 0.85)",    # Rose
]

CHART_BORDER_COLORS = [c.replace("0.85", "1") for c in CHART_COLORS]


def _get_chart_html(chart_config: dict, title: str, width: str = "100%", height: str = "500px") -> str:
    """Generate a self-contained HTML page with a Chart.js chart."""

    config_json = json.dumps(chart_config, indent=2, default=str)

    return f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js"></script>
    <style>
        :root {{
            --bg-primary: #0f172a;
            --bg-secondary: #1e293b;
            --bg-card: #1e293b;
            --text-primary: #f1f5f9;
            --text-secondary: #94a3b8;
            --border: #334155;
            --accent: #6366f1;
        }}

        [data-theme="light"] {{
            --bg-primary: #f8fafc;
            --bg-secondary: #ffffff;
            --bg-card: #ffffff;
            --text-primary: #0f172a;
            --text-secondary: #64748b;
            --border: #e2e8f0;
            --accent: #6366f1;
        }}

        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 2rem;
        }}

        .header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 100%;
            max-width: 1000px;
            margin-bottom: 1.5rem;
        }}

        h1 {{
            font-size: 1.5rem;
            font-weight: 600;
            color: var(--text-primary);
        }}

        .theme-toggle {{
            background: var(--bg-secondary);
            border: 1px solid var(--border);
            color: var(--text-primary);
            padding: 0.5rem 1rem;
            border-radius: 8px;
            cursor: pointer;
            font-size: 0.875rem;
            transition: all 0.2s ease;
        }}

        .theme-toggle:hover {{
            border-color: var(--accent);
        }}

        .chart-container {{
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 16px;
            padding: 2rem;
            width: 100%;
            max-width: 1000px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }}

        canvas {{
            width: {width} !important;
            height: {height} !important;
        }}

        .footer {{
            margin-top: 1.5rem;
            color: var(--text-secondary);
            font-size: 0.75rem;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <button class="theme-toggle" onclick="toggleTheme()">Toggle Theme</button>
    </div>
    <div class="chart-container">
        <canvas id="chart"></canvas>
    </div>
    <div class="footer">
        Generated by NL-to-SQL MCP Server &middot; {datetime.now().strftime("%Y-%m-%d %H:%M")}
    </div>

    <script>
        const config = {config_json};

        // Apply theme-aware defaults
        const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
        const textColor = isDark ? '#f1f5f9' : '#0f172a';
        const gridColor = isDark ? 'rgba(148, 163, 184, 0.1)' : 'rgba(15, 23, 42, 0.1)';

        if (config.options) {{
            if (config.options.plugins && config.options.plugins.legend) {{
                config.options.plugins.legend.labels = config.options.plugins.legend.labels || {{}};
                config.options.plugins.legend.labels.color = textColor;
            }}
            if (config.options.scales) {{
                for (const axis of Object.values(config.options.scales)) {{
                    axis.ticks = axis.ticks || {{}};
                    axis.ticks.color = textColor;
                    axis.grid = axis.grid || {{}};
                    axis.grid.color = gridColor;
                }}
            }}
        }}

        const ctx = document.getElementById('chart').getContext('2d');
        let chart = new Chart(ctx, config);

        function toggleTheme() {{
            const html = document.documentElement;
            const current = html.getAttribute('data-theme');
            const next = current === 'dark' ? 'light' : 'dark';
            html.setAttribute('data-theme', next);

            const newTextColor = next === 'dark' ? '#f1f5f9' : '#0f172a';
            const newGridColor = next === 'dark' ? 'rgba(148, 163, 184, 0.1)' : 'rgba(15, 23, 42, 0.1)';

            if (config.options && config.options.plugins && config.options.plugins.legend) {{
                config.options.plugins.legend.labels = config.options.plugins.legend.labels || {{}};
                config.options.plugins.legend.labels.color = newTextColor;
            }}
            if (config.options && config.options.scales) {{
                for (const axis of Object.values(config.options.scales)) {{
                    axis.ticks = axis.ticks || {{}};
                    axis.ticks.color = newTextColor;
                    axis.grid = axis.grid || {{}};
                    axis.grid.color = newGridColor;
                }}
            }}

            chart.destroy();
            chart = new Chart(ctx, config);
        }}
    </script>
</body>
</html>"""


def generate_chart(
    data: dict,
    chart_type: str,
    x_column: str,
    y_columns: list[str],
    title: str,
    output_dir: str = "charts",
) -> str:
    """
    Generate a self-contained HTML chart file.

    Args:
        data: Query result dict with 'columns' and 'rows'.
        chart_type: One of bar, line, pie, doughnut, scatter, horizontalBar.
        x_column: Column name for X-axis labels.
        y_columns: Column names for Y-axis values.
        title: Chart title.
        output_dir: Directory to save the chart HTML file.

    Returns:
        Absolute path to the generated HTML file.
    """
    columns = data["columns"]
    rows = data["rows"]

    # Get column indices
    x_idx = columns.index(x_column) if x_column in columns else 0
    y_indices = []
    for yc in y_columns:
        if yc in columns:
            y_indices.append(columns.index(yc))
        elif len(columns) > 1:
            y_indices.append(1)

    if not y_indices:
        y_indices = [1] if len(columns) > 1 else [0]

    # Extract data
    labels = [str(row[x_idx]) for row in rows]

    datasets = []
    for i, y_idx in enumerate(y_indices):
        col_name = columns[y_idx] if y_idx < len(columns) else f"Series {i + 1}"
        values = []
        for row in rows:
            val = row[y_idx]
            try:
                values.append(float(val))
            except (TypeError, ValueError):
                values.append(0)

        color_idx = i % len(CHART_COLORS)

        dataset = {
            "label": col_name,
            "data": values,
            "backgroundColor": CHART_COLORS[color_idx] if chart_type in ("bar", "horizontalBar", "line") else CHART_COLORS[:len(values)],
            "borderColor": CHART_BORDER_COLORS[color_idx] if chart_type in ("bar", "horizontalBar", "line") else CHART_BORDER_COLORS[:len(values)],
            "borderWidth": 2,
        }

        if chart_type == "line":
            dataset["fill"] = True
            dataset["tension"] = 0.4
            dataset["pointRadius"] = 4
            dataset["pointHoverRadius"] = 6

        if chart_type == "scatter":
            scatter_data = []
            for row in rows:
                try:
                    scatter_data.append({
                        "x": float(row[x_idx]),
                        "y": float(row[y_idx]),
                    })
                except (TypeError, ValueError):
                    continue
            dataset["data"] = scatter_data

        datasets.append(dataset)

    # Map chart type to Chart.js type
    chartjs_type = chart_type
    if chart_type == "horizontalBar":
        chartjs_type = "bar"

    config = {
        "type": chartjs_type,
        "data": {
            "labels": labels,
            "datasets": datasets,
        },
        "options": {
            "responsive": True,
            "maintainAspectRatio": False,
            "plugins": {
                "legend": {
                    "display": len(datasets) > 1 or chart_type in ("pie", "doughnut"),
                    "position": "top",
                },
                "title": {
                    "display": False,
                },
            },
        },
    }

    # Add scales for non-radial charts
    if chart_type not in ("pie", "doughnut"):
        config["options"]["scales"] = {
            "x": {
                "display": True,
            },
            "y": {
                "display": True,
                "beginAtZero": True,
            },
        }

    if chart_type == "horizontalBar":
        config["options"]["indexAxis"] = "y"

    # Generate HTML
    html = _get_chart_html(config, title)

    # Save to file
    os.makedirs(output_dir, exist_ok=True)
    safe_title = "".join(c if c.isalnum() or c in (" ", "-", "_") else "" for c in title)
    safe_title = safe_title.replace(" ", "_").lower()[:60]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{safe_title}_{timestamp}.html"
    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)

    return os.path.abspath(filepath)


def generate_dashboard(
    charts: list[dict],
    name: str,
    output_dir: str = "dashboards",
) -> str:
    """
    Generate a multi-chart dashboard HTML page.

    Args:
        charts: List of dicts, each with 'title', 'config' (Chart.js config).
        name: Dashboard name.
        output_dir: Directory to save the dashboard HTML file.

    Returns:
        Absolute path to the generated HTML file.
    """
    chart_blocks = []
    for i, chart in enumerate(charts):
        config_json = json.dumps(chart["config"], indent=2, default=str)
        chart_blocks.append(f"""
            <div class="chart-card">
                <h3>{chart['title']}</h3>
                <div class="chart-wrapper">
                    <canvas id="chart-{i}"></canvas>
                </div>
            </div>
            <script>
                (function() {{
                    const config = {config_json};
                    const ctx = document.getElementById('chart-{i}').getContext('2d');
                    new Chart(ctx, config);
                }})();
            </script>
        """)

    charts_html = "\n".join(chart_blocks)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    dashboard_html = f"""<!DOCTYPE html>
<html lang="en" data-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{name} — Dashboard</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js"></script>
    <style>
        :root {{
            --bg-primary: #0f172a;
            --bg-secondary: #1e293b;
            --bg-card: #1e293b;
            --text-primary: #f1f5f9;
            --text-secondary: #94a3b8;
            --border: #334155;
            --accent: #6366f1;
        }}

        [data-theme="light"] {{
            --bg-primary: #f8fafc;
            --bg-secondary: #ffffff;
            --bg-card: #ffffff;
            --text-primary: #0f172a;
            --text-secondary: #64748b;
            --border: #e2e8f0;
            --accent: #6366f1;
        }}

        * {{ margin: 0; padding: 0; box-sizing: border-box; }}

        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            padding: 2rem;
        }}

        .dashboard-header {{
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1400px;
            margin: 0 auto 2rem;
        }}

        h1 {{
            font-size: 2rem;
            font-weight: 700;
            background: linear-gradient(135deg, var(--accent), #a78bfa);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }}

        .dashboard-meta {{
            color: var(--text-secondary);
            font-size: 0.875rem;
        }}

        .theme-toggle {{
            background: var(--bg-secondary);
            border: 1px solid var(--border);
            color: var(--text-primary);
            padding: 0.5rem 1rem;
            border-radius: 8px;
            cursor: pointer;
            font-size: 0.875rem;
            transition: all 0.2s ease;
        }}

        .theme-toggle:hover {{
            border-color: var(--accent);
        }}

        .dashboard-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(500px, 1fr));
            gap: 1.5rem;
            max-width: 1400px;
            margin: 0 auto;
        }}

        .chart-card {{
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 16px;
            padding: 1.5rem;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
            transition: transform 0.2s ease, box-shadow 0.2s ease;
        }}

        .chart-card:hover {{
            transform: translateY(-2px);
            box-shadow: 0 8px 25px -5px rgba(0, 0, 0, 0.2);
        }}

        .chart-card h3 {{
            font-size: 1rem;
            font-weight: 600;
            margin-bottom: 1rem;
            color: var(--text-primary);
        }}

        .chart-wrapper {{
            position: relative;
            height: 350px;
        }}

        canvas {{
            width: 100% !important;
            height: 100% !important;
        }}

        @media (max-width: 768px) {{
            .dashboard-grid {{
                grid-template-columns: 1fr;
            }}
            .dashboard-header {{
                flex-direction: column;
                gap: 1rem;
                text-align: center;
            }}
        }}
    </style>
</head>
<body>
    <div class="dashboard-header">
        <div>
            <h1>{name}</h1>
            <p class="dashboard-meta">Generated {timestamp} &middot; {len(charts)} charts</p>
        </div>
        <button class="theme-toggle" onclick="toggleTheme()">Toggle Theme</button>
    </div>
    <div class="dashboard-grid">
        {charts_html}
    </div>

    <script>
        function toggleTheme() {{
            const html = document.documentElement;
            const current = html.getAttribute('data-theme');
            html.setAttribute('data-theme', current === 'dark' ? 'light' : 'dark');
        }}
    </script>
</body>
</html>"""

    os.makedirs(output_dir, exist_ok=True)
    safe_name = "".join(c if c.isalnum() or c in (" ", "-", "_") else "" for c in name)
    safe_name = safe_name.replace(" ", "_").lower()[:60]
    timestamp_file = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{safe_name}_{timestamp_file}.html"
    filepath = os.path.join(output_dir, filename)

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(dashboard_html)

    return os.path.abspath(filepath)
